### ISSUE TITLE
Remove defaults for id-proxy

### ISSUE THREAD

**Issue by lem-onade** [digita-ai/dgt-id-broker#351]
In Dockerfile and main.ts, remove all(?) default values.

Document which arguments should be passed, or throw clear errors when a necessary arg is missing

more info: @woutermont 

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=863711983) by [Unito](https://www.unito.io)

**Comment by johannadm** [comment]
Already fixed in main.ts and won't be removed in dockerfile because this way we signal that they can be overwritten in the CMD claim.
